[package]
name = "sn_dbc"
version = "2.1.0"
description = "Safe Network DBC"
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_dbc"
documentation = "https://docs.rs/sn_dbc"
keywords = [ "Safe", "Network", "SafeNetwork", "SafeUrl", "XorUrl" ]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
edition = "2018"

[features]
dkg = [ "bls_dkg" ]

[dependencies]
serde_json = "1.0.64"
thiserror = "1.0.24"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.7.1"
rand8 = { package = "rand", version = "0.8.0" }
hex = "0.4.3"
bulletproofs = "4.0.0"
curve25519-dalek-ng = "4.0.1"
merlin = "3.0.0"
bincode = "1.3.3"
blsttc = "2.3.0"

  [dependencies.bls_dkg]
  version = "~0.5"
  optional = true

  [dependencies.tiny-keccak]
  version = "2.0.0"
  features = [ "sha3" ]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

[patch.crates-io]
# Use this branch until it is merged into bls_dkg master.
bls_dkg = { git = "https://github.com/maidsafe/bls_dkg", branch="blsttc_2_3_0_pr" }

[dev-dependencies]
criterion = "0.3"
anyhow = "1.0.40"
rustyline = "8.0.0"
serde = "1.0.126"
rand = "0.7.1"
bincode = "1.3.3"
xor_name = "1.2.0"
hex = "0.4.3"

  [dev-dependencies.sn_dbc]
  path = "."
  features = [ "dkg" ]

[[bench]]
name = "reissue"
harness = false
required-features = [ "dkg" ]

[[example]]
name = "mint-repl"
path = "examples/mint-repl/mint-repl.rs"
