[package]
name = "sn_dbc"
version = "2.9.2"
description = "Safe Network DBC"
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_dbc"
documentation = "https://docs.rs/sn_dbc"
keywords = [ "Safe", "Network", "SafeNetwork", "SafeUrl", "XorUrl" ]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
edition = "2018"

[features]
dkg = [ "bls_dkg" ]

[dependencies]
serde_json = "1.0.64"
thiserror = "1.0.24"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.7.1"
#blst_ringct = {git="https://github.com/maidsafe/blst-ringct"}
blst_ringct = {path="/home/danda/dev/maidsafe/blst-ringct"}
blsttc = "3.3.0"
hex = "0.4.3"
#blstrs = "0.4.1"
blstrs = { git = "https://github.com/davidrusu/blstrs.git", branch="bulletproofs-fixes" }
bulletproofs = { git = "https://github.com/davidrusu/blst-bulletproofs.git", branch="bls12-381-curve" }
rand_core = "0.6.3"


  [dependencies.rand8]
  package = "rand"
  version = "0.8.0"

  [dependencies.bls_dkg]
  version = "~0.7"
  optional = true

  [dependencies.tiny-keccak]
  version = "2.0.0"
  features = [ "sha3" ]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

[dev-dependencies]
criterion = "0.3"
anyhow = "1.0.40"
serde = "1.0.126"
rand = "0.7.1"
rustyline = "8.0.0"
bincode = "1.3.3"

  [dev-dependencies.sn_dbc]
  path = "."
  features = [ "dkg" ]

[target."cfg(unix)".dev-dependencies]
termios = "0.3.3"

[[bench]]
name = "reissue"
harness = false
required-features = [ "dkg" ]

#[[example]]
#name = "mint-repl"
#path = "examples/mint-repl/mint-repl.rs"
